title: Augustin Saah
email: augustinsaah@gmail.com
phone: 301-802-8146

description: Website of Augustin Saah, candidate for House of Delegates in District 47B.
url: augustin-site
# url: http://long-haul.netlify.app


# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

navigation:
  - title: Home
    url: \#
  - title: About
    url: \#about
  - title: Contact
    url: \#contact
  # - title: +1(301)802-8146
  #   url: /contact
  # - title: My email @email.com
  #   url: /contact

# social:
#   twitter: brianmaierjr
#   facebook: brianmaierjr
#   email: brimaidesigns@gmail.com

google_analytics: "UA-58263416-1"